"""Phase 4b §4.2 #16-#23: opt-in helpers built on top of the core SDK.

The ``extras`` subpackage holds spatial geometry, advanced filtering,
batch processing, asset export/import, color helpers, and the API-warning
registry. They are deliberately a sibling of the core resources rather than
methods on :class:`canvus_sdk.Client` so the typed surface stays small and
the optional dependencies stay opt-in.

Quick start::

    from canvus_sdk.extras import (
        BatchOperationBuilder,
        BatchProcessor,
        CrossCanvasSearch,
        Filter,
        Rectangle,
        WidgetExporter,
        WidgetImporter,
        find_widgets_by_text,
        widget_bounding_box,
    )
"""

from __future__ import annotations

from .batch import (
    BatchConfig,
    BatchOperation,
    BatchOperationBuilder,
    BatchOperationType,
    BatchProcessor,
    BatchResult,
    BatchSummary,
    summarize,
)
from .color import (
    COLOR_BLACK,
    COLOR_BLUE,
    COLOR_CYAN,
    COLOR_DARK_GRAY,
    COLOR_GRAY,
    COLOR_GREEN,
    COLOR_LIGHT_GRAY,
    COLOR_MAGENTA,
    COLOR_RED,
    COLOR_TRANSPARENT,
    COLOR_WHITE,
    COLOR_YELLOW,
    color_to_rgb,
    color_to_rgba,
    color_with_alpha,
    normalize_color,
    rgba_to_color,
    validate_color,
)
from .export import (
    ExportedWidgetSet,
    WidgetExporter,
    export_widgets_to_folder,
)
from .filters import (
    Condition,
    Filter,
    FilterOperator,
    combine_filters,
    create_filter,
    create_spatial_filter,
    create_text_filter,
    create_widget_type_filter,
    create_wildcard_filter,
)
from .geometry import (
    Point,
    Rectangle,
    Size,
    WidgetLike,
    contains,
    distance_between_widgets,
    find_widgets_containing_point,
    find_widgets_in_area,
    get_canvas_bounds,
    get_intersection,
    get_union,
    get_widget_intersection,
    get_widget_union,
    intersects,
    touches,
    widget_bounding_box,
    widget_contains,
    widgets_intersect,
    widgets_touch,
)
from .import_ import (
    WidgetImporter,
    import_widgets_from_folder,
)
from .search import (
    CrossCanvasSearch,
    SearchError,
    SearchResult,
    find_widgets_across_canvases,
    find_widgets_by_property,
    find_widgets_by_text,
    find_widgets_by_type,
)
from .search import (
    find_widgets_in_area as find_widgets_in_area_across_canvases,
)
from .warnings import (
    WARNING_IMAGE_ASPECT_RATIO_NOT_PRESERVED,
    WARNING_NOTE_TITLE_NOT_EXPOSED,
    WARNING_PDF_SIZE_BUG,
    WARNING_TABLE_GRID_SIZE_IMMUTABLE,
    WARNING_VIDEO_ASPECT_RATIO_NOT_PRESERVED,
    WARNING_VIDEO_INPUT_TITLE_NOT_EXPOSED,
    APIWarning,
    disable_api_warnings,
    enable_api_warnings,
    reset_warnings,
    warn_always,
    warn_once,
)
from .widget_operations import (
    BatchWidgetOperations,
    SpatialTolerance,
    WidgetOperation,
    WidgetZone,
    WidgetZoneManager,
    calculate_widget_density,
    create_spatial_group,
    find_widget_clusters,
)

__all__ = [
    "COLOR_BLACK",
    "COLOR_BLUE",
    "COLOR_CYAN",
    "COLOR_DARK_GRAY",
    "COLOR_GRAY",
    "COLOR_GREEN",
    "COLOR_LIGHT_GRAY",
    "COLOR_MAGENTA",
    "COLOR_RED",
    "COLOR_TRANSPARENT",
    "COLOR_WHITE",
    "COLOR_YELLOW",
    "WARNING_IMAGE_ASPECT_RATIO_NOT_PRESERVED",
    "WARNING_NOTE_TITLE_NOT_EXPOSED",
    "WARNING_PDF_SIZE_BUG",
    "WARNING_TABLE_GRID_SIZE_IMMUTABLE",
    "WARNING_VIDEO_ASPECT_RATIO_NOT_PRESERVED",
    "WARNING_VIDEO_INPUT_TITLE_NOT_EXPOSED",
    "APIWarning",
    "BatchConfig",
    "BatchOperation",
    "BatchOperationBuilder",
    "BatchOperationType",
    "BatchProcessor",
    "BatchResult",
    "BatchSummary",
    "BatchWidgetOperations",
    "Condition",
    "CrossCanvasSearch",
    "ExportedWidgetSet",
    "Filter",
    "FilterOperator",
    "Point",
    "Rectangle",
    "SearchError",
    "SearchResult",
    "Size",
    "SpatialTolerance",
    "WidgetExporter",
    "WidgetImporter",
    "WidgetLike",
    "WidgetOperation",
    "WidgetZone",
    "WidgetZoneManager",
    "calculate_widget_density",
    "color_to_rgb",
    "color_to_rgba",
    "color_with_alpha",
    "combine_filters",
    "contains",
    "create_filter",
    "create_spatial_filter",
    "create_spatial_group",
    "create_text_filter",
    "create_widget_type_filter",
    "create_wildcard_filter",
    "disable_api_warnings",
    "distance_between_widgets",
    "enable_api_warnings",
    "export_widgets_to_folder",
    "find_widget_clusters",
    "find_widgets_across_canvases",
    "find_widgets_by_property",
    "find_widgets_by_text",
    "find_widgets_by_type",
    "find_widgets_containing_point",
    "find_widgets_in_area",
    "find_widgets_in_area_across_canvases",
    "get_canvas_bounds",
    "get_intersection",
    "get_union",
    "get_widget_intersection",
    "get_widget_union",
    "import_widgets_from_folder",
    "intersects",
    "normalize_color",
    "reset_warnings",
    "rgba_to_color",
    "summarize",
    "touches",
    "validate_color",
    "warn_always",
    "warn_once",
    "widget_bounding_box",
    "widget_contains",
    "widgets_intersect",
    "widgets_touch",
]
